### An end-to-end Scikit-Learn workflow

In [ ]:
# Standard imports
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
# 1. Get the data ready
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head(1)

In [ ]:
# Create X (features matrix)
x = heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease.target

In [ ]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# To see the default hyperparameters
clf.get_params();

In [ ]:
# 3. Split the dataset to training and testing data
from sklearn.model_selection import train_test_split

x_train , x_test, y_train, y_test = train_test_split(x, y, test_size=0.2) 

In [ ]:
# 4. Fit the model to the training data
clf.fit(x_train, y_train);

In [ ]:
# 5. Make a prediction - This will not work as the shaope does not match - always use the test data
y_label = clf.predict(np.array([0, 2, 3, 4]))

In [18]:
# Make a prediction
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [19]:
# The actual y/labels of test data
np.array(y_test)

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [20]:
# 6. Evaluate the model on the training data and test data

# using the train data (should == 1)
clf.score(x_train, y_train)

1.0

In [26]:
# using the test data (should != 1)
clf.score(x_test, y_test)

0.6885245901639344

In [28]:
# 7. Other mterics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Overall report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      0.48      0.58        27
           1       0.67      0.85      0.75        34

    accuracy                           0.69        61
   macro avg       0.70      0.67      0.67        61
weighted avg       0.70      0.69      0.68        61



In [30]:
# confusion matrix
print(confusion_matrix(y_test, y_pred))

[[13 14]
 [ 5 29]]


In [31]:
# Accuracy
accuracy_score(y_test, y_pred)

0.6885245901639344

In [38]:
# 8. Improve a model

# Try different amount of n_estimators
np.random.seed(42)

for i in range(10, 110, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train, y_train)
    print(f"Model accuracy on test set: {clf.score(x_test, y_test) * 100:.2f}%")
    print("")
    

Trying model with 10 estimators...
Model accuracy on test set: 81.97%

Trying model with 20 estimators...
Model accuracy on test set: 68.85%

Trying model with 30 estimators...
Model accuracy on test set: 68.85%

Trying model with 40 estimators...
Model accuracy on test set: 72.13%

Trying model with 50 estimators...
Model accuracy on test set: 73.77%

Trying model with 60 estimators...
Model accuracy on test set: 72.13%

Trying model with 70 estimators...
Model accuracy on test set: 70.49%

Trying model with 80 estimators...
Model accuracy on test set: 73.77%

Trying model with 90 estimators...
Model accuracy on test set: 73.77%

Trying model with 100 estimators...
Model accuracy on test set: 72.13%



In [40]:
# 6. Save a model and load it
import pickle

pickle.dump(clf, open("random_forst_model_1.pkl", "wb"))

In [41]:
# import 
loaded_model = pickle.load(open("random_forst_model_1.pkl", "rb"))

In [43]:
loaded_model.score(x_test, y_test)

0.7213114754098361